const STOP = new Set("a an and are as at be by can do does for from how i if in is it me my of on or our the this to under was what when which with you your".split(" "));
const SYNONYMS = { money:["refund","refundable"], back:["refund"], arrive:["arrival","check-in"], arrival:["check-in"], cancel:["cancellation","cancellations"], cancelling:["cancellation","cancellations"], canceled:["cancellation"], refunded:["refund","refundable"], transfer:["shuttle","transport"] };
let chunks = [];

const normalize = text => text.toLowerCase().replace(/[^a-z0-9-]+/g," ").trim();
function tokens(text, expand=false){const out=[];for(const word of normalize(text).split(/\s+/)){if(!word||STOP.has(word))continue;out.push(word);if(expand&&SYNONYMS[word])out.push(...SYNONYMS[word]);}return new Set(out)}
function yearOf(chunk){return String(chunk.metadata?.effective_from||"").slice(0,4)}
function lexicalScore(question,chunk,expand=false){const q=tokens(question,expand);const hay=tokens(`${chunk.title} ${chunk.section} ${yearOf(chunk)} ${chunk.text}`,expand);let hits=0;q.forEach(t=>{if(hay.has(t))hits++});return hits/Math.max(1,Math.sqrt(q.size*hay.size))}
function rank(question,expand){return chunks.map(c=>({...c,raw:lexicalScore(question,c,expand)})).sort((a,b)=>b.raw-a.raw)}
function retrieve(question){const keyword=rank(question,false),semantic=rank(question,true);const scores=new Map();keyword.slice(0,10).forEach((c,i)=>scores.set(c.chunk_id,(scores.get(c.chunk_id)||0)+1/(60+i+1)));semantic.slice(0,10).forEach((c,i)=>scores.set(c.chunk_id,(scores.get(c.chunk_id)||0)+1/(60+i+1)));return chunks.map(c=>({...c,rrf:scores.get(c.chunk_id)||0,keyword:lexicalScore(question,c,false),semantic:lexicalScore(question,c,true)})).sort((a,b)=>b.rrf-a.rrf)}
function ambiguity(question,results){if(/\b20\d{2}\b/.test(question))return null;const top=results[0];if(!top||top.keyword<.12)return null;const years=[...new Set(chunks.filter(c=>c.title===top.title&&c.section===top.section).map(yearOf).filter(Boolean))].sort();return years.length>1?years:null}
function pipelineTrace(active){const names=["QUERY","HYBRID RETRIEVAL","RRF","VERSION GUARD","EVIDENCE"];return `<div class="trace">${names.map((n,i)=>`<span class="${i<=active?'done':''}">${String(i+1).padStart(2,'0')} ${n}</span>`).join("")}</div>`}
function sourceHtml(item){return `<div class="source-card"><div class="source-head"><strong>[1] ${item.title} · ${item.section}</strong><span>${yearOf(item)} POLICY</span></div><p>${item.text}</p><div class="scores"><span>semantic proxy ${item.semantic.toFixed(3)}</span><span>keyword ${item.keyword.toFixed(3)}</span><span>RRF ${item.rrf.toFixed(5)}</span></div></div>`}
function run(){const input=document.querySelector("#question"),panel=document.querySelector("#result-panel"),button=document.querySelector("#ask-button");const question=input.value.trim();if(!question)return;button.disabled=true;button.textContent="Running…";setTimeout(()=>{const results=retrieve(question),top=results[0],years=ambiguity(question,results);panel.classList.remove("empty");if(years){panel.innerHTML=`${pipelineTrace(3)}<div class="answer-box warning"><span class="answer-label">CLARIFICATION NEEDED</span><p>Which policy year applies? Available years: ${years.join(", ")}.</p></div>${sourceHtml(top)}`;}else if(!top||top.keyword<.075){panel.innerHTML=`${pipelineTrace(2)}<div class="answer-box abstain"><span class="answer-label">ABSTAINED</span><p>I don't have enough information in the provided policies.</p></div><div class="source-card"><div class="source-head"><strong>Why generation was skipped</strong><span>INSUFFICIENT EVIDENCE</span></div><p>The highest retrieval signal did not pass this browser demo's support check. The full Python pipeline makes this decision with a development-calibrated cross-encoder threshold.</p></div>`;}else{panel.innerHTML=`${pipelineTrace(4)}<div class="answer-box"><span class="answer-label">GROUNDED ANSWER</span><p>According to the retrieved policy: ${top.text} <strong>[1]</strong></p></div>${sourceHtml(top)}`;}button.disabled=false;button.innerHTML="Run <span>→</span>";panel.scrollIntoView({behavior:"smooth",block:"nearest"});},360)}
fetch("/web/chunks.json").then(r=>r.json()).then(data=>{chunks=data}).catch(()=>{document.querySelector("#result-panel").innerHTML="<p>Policy index could not be loaded.</p>"});
document.querySelector("#ask-button").addEventListener("click",run);
document.querySelector("#question").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();run()}});
document.querySelectorAll("[data-question]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelector("#question").value=btn.dataset.question;run()}));
